name: lattice_env

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - libstdcxx-ng>=14
  - numpy=1.26.*
  - scipy
  - scikit-learn
  - matplotlib
  - pandas
  - polars
  - joblib
  - tabulate
  - tqdm
  - wandb
  - chardet
  - fpylll
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu128
    - torch==2.7.0+cu128
    - torchvision==0.22.0+cu128
    - torchaudio==2.7.0+cu128
    - torchmetrics
    - einops
